#pragma once

#define GAME_WIDTH 288
#define GAME_HEIGHT 512
#define GAME_START 1
#define GAME_OVER 0
#define GAME_INIT -1
#define PIPE_WIDTH 52
#define PIPE_START_WIDTH 500
#define PIPE_BETWEEN_WIDTH 170
#define PIPE_SPACE 50
#define PIPE_VARIATION_RANGE 200